spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/moderation
    username: moderation
    password: moderation
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name:
      moderation-worker
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: moderation-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "streamguard.*"
        spring.json.value.default.type: streamguard.moderationworker.kafka.dto.CommentEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1
server:
  port: 8081