spring:
  application:
    name: stats-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stats-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "streamguard.*"
        spring.json.value.default.type: streamguard.statsservice.kafka.dto.ModerationEvent
server:
  port: 8083